sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t sankethns/docker-react .

script:
    - docker run -e CI=true sankethns/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1b"
    app: "Docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-943138244620"
    bucket_path: "Docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
